services:
  db:
    image: postgres:latest
    container_name: peverel_db
    environment:
      POSTGRES_USER: peverel
      POSTGRES_PASSWORD: peverel
      POSTGRES_DB: peverel
    volumes:
      - peverel_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "5432"

  peverel:
    environment:
      SERVER_PORT: 8080
      LOG_LEVEL: info
      LOG_OUTPUT: stdout
      DB_CONN_STRING: "postgresql://peverel:peverel@db/peverel?sslmode=disable"
    build:
      context: .
      dockerfile: Dockerfile-peverel
    container_name: peverel_app
    ports:
      - "8081:8080"
    depends_on:
      - db

  notifier:
    environment:
      DB_CONN_STRING: "postgresql://peverel:peverel@localhost/peverel?sslmode=disable"
      EMAIL_SENDER: ${NOTIFIER_EMAIL_SENDER}
      EMAIL_RECIPIENTS: ${NOTIFIER_EMAIL_RECIPIENTS}
      SMTP_SERVER: ${NOTIFIER_SMTP_SERVER}
      SMTP_PORT: ${NOTIFIER_SMTP_PORT}
      SMTP_USERNAME: ${NOTIFIER_SMTP_USERNAME}
      SMTP_PASSWORD: ${NOTIFIER_SMTP_PASSWORD}
      SCHEDULED_TIME: "05:00"
      SCHEDULED_HOURS: 24
      LOG_LEVEL: info
      LOG_OUTPUT: stdout
    build:
      context: .
      dockerfile: Dockerfile-notifier
    container_name: notifier_app
    depends_on:
      - db

volumes:
  peverel_data: