services:
  db:
    image: postgres:latest
    container_name: peverel_db
    environment:
      POSTGRES_USER: peverel
      POSTGRES_PASSWORD: peverel
      POSTGRES_DB: peverel
    volumes:
      - peverel_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "5432"

  app:
    environment:
      PEVEREL_PORT: 8080
      PEVEREL_LOG_LEVEL: info
      PEVEREL_LOG_OUTPUT: stdout
      PEVEREL_DB_CONN_STRING: "postgresql://peverel:peverel@db/peverel?sslmode=disable"
    build:
      context: .
      dockerfile: Dockerfile-peverel
    container_name: peverel_app
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  peverel_data: